# This section tells Netlify how to build your Vite project.
[build]
  command = "vite build"
  publish = "dist"

# This is the "catch-all" rule for your Single-Page Application (SPA).
# It serves your index.html for any path requested. This is essential
# for client-side routing (like your hash-based navigation) to work correctly
# when a user refreshes the page or navigates directly to a deep link.
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200